Add gaps in time serie
kartoza/django-bims pull request #2957
Opened 2022-02-22 20:33 UTC by Fanevanjanahary

for #2953

2022-02-22 20:38 UTC, Fanevanjanahary commented
Hi @dimasciput I'm not sure how to calculate the indicators when there is no value, for a moment I just exclude it from the query

2022-02-24 04:11 UTC, dimasciput commented
@Fanevanjanahary yes please only update it from the frontend, you don't need check if value is null in the backend.

2022-02-24 04:12 UTC, dimasciput approved these changes

2022-02-24 04:12 UTC, dimasciput commented on bims/migrations/0301_auto_20220222_1415.py
> +            field=models.FloatField(blank=True, help_text='Water temperature data, if daily data then this is the Mean value.', null=True),
@Fanevanjanahary please don't make it nullable here.

2022-03-01 08:58 UTC, dimasciput requested changes

2022-03-01 08:58 UTC, dimasciput commented on bims/static/js/non_requirejs/water_temperature.js
> +        console.log(data['mean_7'])
@Fanevanjanahary please remove this

2022-04-01 04:39 UTC, dimasciput commented
@Fanevanjanahary can you get all days in the frontend instead to reduce the size of the response from the api?

2022-04-01 06:10 UTC, Fanevanjanahary commented
Hi @dimasciput I changed the date range in queryset and now it gets all the data, including the date end

Here is a test from this data [H2ROOI-WORCE 01_12_2008 to 03_02_2011.xlsx](https://github.com/kartoza/django-bims/files/8282469/H2ROOI-WORCE.01_12_2008.to.03_02_2011.xlsx) from @helendallas 

![image](https://user-images.githubusercontent.com/12623986/161204794-b46c9198-82f2-45fb-8b85-0cf138afd0c0.png)

![image](https://user-images.githubusercontent.com/12623986/161204979-c66838c1-7ad1-47dc-9761-86beb75ba972.png)

2022-04-01 08:19 UTC, helendallas commented
So, I am not sure we are on the same page here. We are happy to get a shortened time series when data are only for part of a year. We dont need the whole year scale on the x axis. BUT what was happening is the data were only for 2 months, but somehow a graph was generated for the full year.

2022-04-02 04:14 UTC, dimasciput commented
@helendallas got it

@Fanevanjanahary let me continue this ticket

2022-04-02 04:14 UTC, merged